server:
  servlet:
    encoding:
      force: "true"
      enabled: "true"
      charset: UTF-8
    context-path: /
  port: "8080"
logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG
spring:
  jpa:
    database: mysql
    show-sql: "true"
    format-sql: "true"
  datasource:
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://database-1.cd6uosjs1jca.ap-northeast-2.rds.amazonaws.com:3306/chauk?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

kakao:
  clientId: "5e0fdf41faf62182a4e2890e11075505"
  secret: "S3BMW324uWV2vFccAdnP7SZPtKztzQa7"
